# Generated by Django 5.1.3 on 2024-12-09 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_notification_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='customer',
        ),
        migrations.AddField(
            model_name='notification',
            name='CustomUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
