# Generated by Django 5.1.3 on 2024-12-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_restaurant_waiting_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
    ]
